### ISSUE TITLE
the results come from two different models

### ISSUE THREAD

**Issue by backkon** [ZFTurbo/Weighted-Boxes-Fusion#11]
I want to ask, if the results come from two different models, such as Yolo and frcnn,  can I use this method?

**Comment by backkon** [comment]
Because the scores of different models are different, can we directly compare them? Look forward to your reply.

**Comment by ZFTurbo** [comment]
Yes, you can. Actually I used this method many times for ensemble of different models results.

**Comment by backkon** [comment]
Ok, got it! Thanks
