### ISSUE TITLE
How to find the optimal hyper-parameters in the ensembling process

### ISSUE THREAD

**Issue by yutongy98** [ZFTurbo/Weighted-Boxes-Fusion#45]
Hello, I would like to ask how to find the best parameters combination, such as the model importances, IOU threshold when performing the ensemble process? Now I got prediction results from different models and try to ensemble these predictions, but I cannot know how to find the optimal parameters. Any suggestions will be helpful!
Thank you in advance.

**Comment by ZFTurbo** [comment]
I just made set of cycles.

**Comment by 123dddd** [comment]
wow, thanks for the fast response! I understood : )
