### ISSUE TITLE
label list on SSD

### ISSUE THREAD

**Issue by ksmdnl** [ZFTurbo/Weighted-Boxes-Fusion#53]
Hello, I'm building an ensemble object detection model with two SSD head detectors.
In this implementation the labels of the predicted model are stored with the corresponding conf scores and the bbox coordinates. 

In SSD, though, the model doesn't produce the corresponding label during the detection. 

Is there any way to make sense this implementation when using SSD as the detector or does anyone have any input on this matter?
Looking forward for sharing!

**Comment by wra1229** [comment]
rewrite the method ，4 bbox parameters to 8 obb parameters
