### ISSUE TITLE
run NMS on empty bounding box from one of ensembled models

### ISSUE THREAD

**Issue by ramdhan1989** [ZFTurbo/Weighted-Boxes-Fusion#54]
Hi, I tried to ensemble 5 models. if there is no bounding box detected from one of 5 models, the nms gives error as follow :
```
ValueError                                Traceback (most recent call last)
Input In [39], in <cell line: 14>()
     12 lebar = dict_pred[img.split('\\')[-1].split('.')[0]]['image_width']
     13 tinggi = dict_pred[img.split('\\')[-1].split('.')[0]]['image_height']
---> 14 boxes, scores, labels = nms_method(bbox_list, conf_list, cat_list, method=2, weights=weights, iou_thr=0.3, sigma=0.05, thresh=0.001)

File ~\Anaconda3\envs\SiT\lib\site-packages\ensemble_boxes\ensemble_boxes_nms.py:187, in nms_method(boxes, scores, labels, method, iou_thr, sigma, thresh, weights)
    184             scores[i] = (np.array(scores[i]) * weights[i]) / weights.sum()
    186 # We concatenate everything
--> 187 boxes = np.concatenate(boxes)
    188 scores = np.concatenate(scores)
    189 labels = np.concatenate(labels)

File <__array_function__ internals>:5, in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 3 has 1 dimension(s)
```

If I used wbf method, it runs succesfully. is there any solution to run nms in this situation like wbf does. please advise

thank you
regards

**Comment by ZFTurbo** [comment]
Can you put small example which fails?

**Comment by ramdhan1989** [comment]
this is an example 
```

boxes_list = [
    [
        []
    ],
    [
        [0.04, 0.56, 0.84, 0.92]
    ],
]
scores_list = [
    [],
    [0.5]
]
labels_list = [
    [],
    [1]
]
weights = [2, 1]

boxes, scores, labels = nms_method(boxes_list, scores_list, labels_list, method=3, weights=weights, iou_thr=0.5, sigma=0.5, thresh=0.001)
```

**Comment by ZFTurbo** [comment]
It was a little bit incorrect. boxes_list shouldn't contain anything if empty:

```
        boxes_list = [
            [
            ],
            [
                [0.04, 0.56, 0.84, 0.92]
            ],
        ]
        scores_list = [
            [],
            [0.5]
        ]
        labels_list = [
            [],
            [1]
        ]
        weights = [2, 1]

        boxes, scores, labels = nms_method(
            boxes_list,
            scores_list,
            labels_list,
            method=3,
            weights=weights,
            iou_thr=0.5,
            sigma=0.5,
            thresh=0.001
        )
```

I fixed the problem.

**Comment by zhangxgu** [comment]
> It was a little bit incorrect. boxes_list shouldn't contain anything if empty:
> 
> ```
>         boxes_list = [
>             [
>             ],
>             [
>                 [0.04, 0.56, 0.84, 0.92]
>             ],
>         ]
>         scores_list = [
>             [],
>             [0.5]
>         ]
>         labels_list = [
>             [],
>             [1]
>         ]
>         weights = [2, 1]
> 
>         boxes, scores, labels = nms_method(
>             boxes_list,
>             scores_list,
>             labels_list,
>             method=3,
>             weights=weights,
>             iou_thr=0.5,
>             sigma=0.5,
>             thresh=0.001
>         )
> ```
> 
> I fixed the problem.

I meet this problem too. This example can not work for me, it still comes to the ValueError: all the input arrays must have same number of dimensions.
Hope you can give me some advice about how to fix it

**Comment by ZFTurbo** [comment]
The fix is in repository alredy.
