### ISSUE TITLE
about map_boxes in run_benchmark_oid.py

### ISSUE THREAD

**Issue by xiaogezi-L** [ZFTurbo/Weighted-Boxes-Fusion#62]
![image](https://github.com/ZFTurbo/Weighted-Boxes-Fusion/assets/130552433/f6716de7-39f4-4201-bc9d-00fb0017226f)
i couldn't find the "map_boxes"

**Comment by ZFTurbo** [comment]
It's here:
https://github.com/ZFTurbo/Mean-Average-Precision-for-Boxes

`pip install map-boxes`

**Comment by xiaogezi-L** [comment]
thankyou
