### ISSUE TITLE
Sould the "break" change to "continue"

### ISSUE THREAD

**Issue by EvanAlbee** [ZFTurbo/Weighted-Boxes-Fusion#8]
https://github.com/ZFTurbo/Weighted-Boxes-Fusion/blob/d48402e487dcdf9a5b4e519ed0ef254f233c3fd6/ensemble_boxes/ensemble_boxes_wbf.py#L35

Hi I do not see why this should  break,if one prediction is bad,we should just ignore instead of jumping out of loop  unless this list is sorted?

Thanks!

**Comment by ZFTurbo** [comment]
Thank you. You found critical bug. I always worked with sorted boxes and missed this potential problem. I fixed the code and update it in pip installation as well.

**Comment by EvanAlbee** [comment]
You are welcomed ! I think we all enjoy the benefit of sharing! cheers
